Society/Models/Security.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Society.Models
{
    public class Security
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Moobile { get; set; }
        public string Image { get; set; }
    }
}

Society/Controllers/SecurityController.cs
 using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Society.Models;
using Society.Context;

namespace Society.Controllers
{
    public class SecurityController : Controller
    {
        private SocietyContext db = new SocietyContext();

        // GET: /Security/
        public ActionResult SecuIndex()
        {
            ViewBag.Index = "active";
            return View(db.Securities.ToList());
        }

        // GET: /Security/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Security/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Email,Moobile,Image")] Security security, HttpPostedFileBase Image)
        {
            if (ModelState.IsValid)
            {
                if (Image != null && Image.ContentLength > 0)
                {
                    try
                    {
                        string fileName = Guid.NewGuid().ToString() + System.IO.Path.GetExtension(Image.FileName);
                        string uploadUrl = Server.MapPath("~/Picture");
                        Image.SaveAs(Path.Combine(uploadUrl, fileName));
                        security.Image = "Picture/" + fileName;
                    }
                    catch (Exception ex)
                    {
                        ViewBag.Message = "ERROR:" + ex.Message.ToString();
                    }
                }
                security.Name = security.Name;
                security.Email = security.Email;
                security.Moobile = security.Moobile;
                db.Securities.Add(security);
                db.SaveChanges();

            }

            return RedirectToAction("Create", new { message = "Security added Successfully" });
        }

        // GET: /Security/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Security security = db.Securities.Find(id);
            if (security == null)
            {
                return HttpNotFound();
            }
            return View(security);
        }

        // POST: /Security/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Email,Moobile,Image")] Security security, HttpPostedFileBase Image, string pastImage)
        {
            if (ModelState.IsValid)
            {
                if (Image != null && Image.ContentLength > 0)
                {

                    try
                    {
                        string fileName = Guid.NewGuid().ToString() + System.IO.Path.GetExtension(Image.FileName);
                        string uploadUrl = Server.MapPath("~/Picture");
                        Image.SaveAs(Path.Combine(uploadUrl, fileName));
                        security.Image = "Picture/" + fileName;
                    }
                    catch (Exception ex)
                    {
                        ViewBag.Message = "ERROR:" + ex.Message.ToString();
                    }
                }
                else
                {
                    security.Image = pastImage;
                }
                db.Entry(security).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("SecuIndex");
            }
            return View(security);
        }

        // GET: /Security/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Security security = db.Securities.Find(id);
            if (security == null)
            {
                return HttpNotFound();
            }
            return View(security);
        }

        // POST: /Security/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Security security = db.Securities.Find(id);
            db.Securities.Remove(security);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Society/Views/Security/Create.cshtml
@model Society.Models.Security

@{
    //Layout = null;
}

<style>
    .design-box {
        margin: 26px;
        background-color: #909090;
        padding: 41px;
        border: 1px steelblue;
        border-radius: 25px;
        color: white;
    }

    .bbt {
        width: 31%;
        margin-left: 21em;
    }

    .warning {
        font-weight: 400;
        padding: 10px;
        border-radius: 9px;
        width: 28em;
        text-align: center;
        box-shadow: -1px 4px 1px 1px #34404c;
        margin-bottom: 11px;
    }

    .error {
        color: red;
    }

    .labd {
        text-align: center;
        padding: 1em;
        background-color: brown;
        color: white;
        font-weight: 700;
        font-size: 27px;
        margin-bottom: 25px;
    }

    .btn {
        color: white;
        font-size: 18px;
        font-weight: 700;
        background-color: orange;
    }

        .btn:hover {
            background-color: brown;
            color: white;
        }
</style>

<div class="container">
    <div class="row">


        <div class="col-md-12 design-box">
            <center>
                @if (ViewBag.Message != null)
                {

                    <div class="warning" style="background-color: #46e86d;" id="warningLabel">
                        <label>@ViewBag.Message</label>
                    </div>

                }
            </center>
            @using (Html.BeginForm("Create", "Security", FormMethod.Post, new { name = "insertForm", id = "insertForm", enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                <div class="form-horizontal">
                    <center>
                        <h3 class="labd">Add Security</h3>
                    </center>
                    @Html.ValidationSummary(true)
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2"> </div>
                        @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
                        <div class="col-md-6">
                            <input name="Name" class="form-control" type="text" id="Name" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2"> </div>
                        @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
                        <div class="col-md-6">
                            <input name="Email" class="form-control" type="text" id="Degree" />
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-2"> </div>
                        @Html.LabelFor(model => model.Image, new { @class = "control-label col-md-2" })
                        <div class="col-md-6">
                            @Html.TextBoxFor(model => model.Image, new { Type = "file" })
                            @Html.ValidationMessageFor(model => model.Image)
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-2"> </div>
                        @Html.LabelFor(model => model.Moobile, new { @class = "control-label col-md-2" })
                        <div class="col-md-6">
                            <input name="Moobile" class="form-control" type="text" id="Moobile" />
                        </div>
                    </div>



                    <div class="form-group row">
                        <div class="col-md-12" style="position: absolute; text-align: center;">
                            <input type="submit" value="Submit" style="width: 23%" class="btn" />
                        </div>
                    </div>
                   
               
            }
        </div>
    </div>
</div>
@section scripts{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script>
        $(document).ready(function () {
            setTimeout(function () {
                $("#warningLabel").hide(1000).empty();
            }, 5000);
        });
        $("#insertForm").validate({
            rules: {
                Name: "required",
                Email: {
                    required: true
                },
                Moobile: "required",
                Image: "required"
            },
            messages: {
                Name: "Please Enter a Name",
                Image: "Please Select an Image",
                Email: {
                    required: "Please Enter Email"
                },
                Moobile: "Please Enter the Number"
            }
        });
    </script>
}

Society/Views/Security/Delete.cshtml
@model Society.Models.Security

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Security</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Moobile)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Moobile)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Image)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Image)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

Society/Views/Security/Edit.cshtml
@model Society.Models.Security

@{
    //Layout = null;
}

<style>
    .design-box {
        margin: 26px;
        background-color: #909090;
        padding: 41px;
        border: 1px steelblue;
        border-radius: 25px;
        color: white;
    }

    .bbt {
        width: 26%;
        margin-left: 3em;
    }

    .labd {
        text-align: center;
        padding: 1em;
        background-color: orchid;
        color: white;
        font-weight: 700;
        font-size: 27px;
        margin-bottom: 25px;
    }

    .btn {
        font-size: 18px;
        font-weight: 700;
    }
</style>

<div class=" container ">
    <div class="row">
        <div class="col-md-12 design-box">
            @using (Html.BeginForm("Edit", "Security", FormMethod.Post, new { name = "insertForm", id = "insertForm", enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                <div class="form-horizontal">
                    <center>
                        <h3 class="labd">Update Security Information</h3>
                    </center>
                    @Html.ValidationSummary(true)
                    <div class="form-group row">
                        <div class="col-md-2"> </div>
                        @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
                        <div class="col-md-6">
                            <input name="Name" class="form-control" type="text" id="Name" value="@Model.Name" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2"> </div>
                        @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
                        <div class="col-md-6">
                            <input name="Email" class="form-control" type="text" id="Email" value="@Model.Email" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2"> </div>
                        @Html.LabelFor(model => model.Image, new { @class = "control-label col-md-2" })
                        <div class="col-md-6">
                            <input type="file" name="Image" />
                            @Html.HiddenFor(model => model.Image, new { @Name = "pastImage" })
                            @Html.ValidationMessageFor(model => model.Image)
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2"> </div>
                        @Html.LabelFor(model => model.Moobile, new { @class = "control-label col-md-2" })
                        <div class="col-md-6">
                            <input name="Moobile" class="form-control" type="text" id="Moobile" value="@Model.Moobile" />
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-12" style="position: absolute; text-align: center;">
                            <input type="submit" value="Edit" style="width: 23%" class="btn btn-primary" />
                        </div>
                    </div>
                    <div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>
@section scripts{
     <script src="~/Scripts/jquery.validate.min.js"></script>
    <script>
        $(document).ready(function () {
            setTimeout(function () {
                $("#warningLabel").hide(1000).empty();
            }, 5000);
        });
    $("#insertForm").validate({
        rules: {
            Name: "required",
            Email: {
                required: true
            },
            Moobile: {
                required: true
            },
            Image: "required"
        },
        messages: {
            Name: "Please Enter a Name",
            Image: "Please Select an Image",
            Email: {
                required: "Please Enter Email"
            },
            Moobile: "Please Enter the Number"
        }
    });
    </script>
}

Society/Views/Security/SecuIndex.cshtml
@model IEnumerable<Society.Models.Security>

@{
    ViewBag.SecuIndex = "active";
}
<link href="~/Content/DataTables/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />
<style>
    .wod {
        width: 90%;
        margin-bottom: 2px;
    }

    .indexdesignbox {
        margin: 30px 30px 30px 30px;
        padding: 30px;
    }

    .newbox {
        width: 90%;
    }

    #datatable {
        text-align: center;
    }
</style>

<div class="indexdesignbox">
    <table id="datatable" class="table table-bordered table-striped table-hover">
        <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Moobile)
            </th>
            <th>
                Action
            </th>
        </tr>
        </thead>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <img style="height: 100px; width: 100px;" src="~/@Html.DisplayFor(modelItem => item.Image)">
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Moobile)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new {id = item.Id}, new {@class = "btn btn-primary wod"})
                    @Html.ActionLink("Add Security", "Create", null, new {@class = "newbox btn btn-warning"})
                </td>
            </tr>
        }
    </table>
</div>
@section scripts{
    <script src="~/Scripts/DataTables/jquery.dataTables.js"></script>
    <script>
        $(document).ready(function () {
            var table = $('#datatable').DataTable();
        });
    </script>
}