Society/Models/Appointment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Society.Models
{
    public class Appointment
    {
        public int Id { get; set; }
        public int PatientId { get; set; }
        public string Date { get; set; }
        public int SpecialistId { get; set; }
        public int DoctorId { get; set; }
        public string Gender { get; set; }
        public string Age { get; set; }
        public string Message { get; set; }
        public int IsApproved { get; set; }
    }
}

Society/Models/Order.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Society.Models
{
    public class Order
    {
        public int Id { get; set; }
        public string ProductCode { get; set; }
        public int ProductAmount { get; set; }
        public string Price { get; set; }
        public string Date { get; set; }
        public string TotalPrice { get; set; }
        public int CustomerId { get; set; }
    }
}

Society/Models/Orderview.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Society.Models
{
    public class Orderview
    {
        public int Id { get; set; }
        public string ProductCode { get; set; }
        public int ProductAmount { get; set; }
        public string Price { get; set; }
        public string Date { get; set; }
        public string TotalPrice { get; set; }
        public string CustomerName { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
    }
}

Society/Models/Security.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Society.Models
{
    public class Security
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Moobile { get; set; }
        public string Image { get; set; }
    }
}

Society/Controllers/SecurityController.cs
 using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Society.Models;
using Society.Context;

namespace Society.Controllers
{
    public class SecurityController : Controller
    {
        private SocietyContext db = new SocietyContext();

        // GET: /Security/
        public ActionResult SecuIndex()
        {
            ViewBag.Index = "active";
            return View(db.Securities.ToList());
        }

        // GET: /Security/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Security/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Email,Moobile,Image")] Security security, HttpPostedFileBase Image)
        {
            if (ModelState.IsValid)
            {
                if (Image != null && Image.ContentLength > 0)
                {
                    try
                    {
                        string fileName = Guid.NewGuid().ToString() + System.IO.Path.GetExtension(Image.FileName);
                        string uploadUrl = Server.MapPath("~/Picture");
                        Image.SaveAs(Path.Combine(uploadUrl, fileName));
                        security.Image = "Picture/" + fileName;
                    }
                    catch (Exception ex)
                    {
                        ViewBag.Message = "ERROR:" + ex.Message.ToString();
                    }
                }
                security.Name = security.Name;
                security.Email = security.Email;
                security.Moobile = security.Moobile;
                db.Securities.Add(security);
                db.SaveChanges();

            }

            return RedirectToAction("Create", new { message = "Security added Successfully" });
        }

        // GET: /Security/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Security security = db.Securities.Find(id);
            if (security == null)
            {
                return HttpNotFound();
            }
            return View(security);
        }

        // POST: /Security/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Email,Moobile,Image")] Security security, HttpPostedFileBase Image, string pastImage)
        {
            if (ModelState.IsValid)
            {
                if (Image != null && Image.ContentLength > 0)
                {

                    try
                    {
                        string fileName = Guid.NewGuid().ToString() + System.IO.Path.GetExtension(Image.FileName);
                        string uploadUrl = Server.MapPath("~/Picture");
                        Image.SaveAs(Path.Combine(uploadUrl, fileName));
                        security.Image = "Picture/" + fileName;
                    }
                    catch (Exception ex)
                    {
                        ViewBag.Message = "ERROR:" + ex.Message.ToString();
                    }
                }
                else
                {
                    security.Image = pastImage;
                }
                db.Entry(security).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("SecuIndex");
            }
            return View(security);
        }

        // GET: /Security/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Security security = db.Securities.Find(id);
            if (security == null)
            {
                return HttpNotFound();
            }
            return View(security);
        }

        // POST: /Security/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Security security = db.Securities.Find(id);
            db.Securities.Remove(security);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Society/Controllers/SocietyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Society.Context;
using Society.Models;

namespace Society.Controllers
{
    public class SocietyController : Controller
    {
        //
        // GET: /Society/
        public ActionResult Index()
        {
            ViewBag.Index = "active";
            return View();
        }

//***********************************************  House *********************************************//
        public ActionResult HouseRent()
        {
            ViewBag.HouseRent = "active";
            List<House> houses;
            using (var ctx = new SocietyContext())
            {
                houses = ctx.Houses.ToList();
            }
            return View(houses);

        }

        public ActionResult HouseRentForm()
        {
            ViewBag.HouseRentForm = "active";
            return View();

        }

        [HttpPost]
        public ActionResult HouseRentForm(BookigHouse bookigHouse)
        {
            using (var ctx = new SocietyContext())
            {
                ctx.BookigHouses.Add(bookigHouse);
                ctx.SaveChanges();
            }

            ViewBag.Message = "Your Booking taken Successfully.";

            return View();

        }

//****************************************** School ***********************************************//
        public ActionResult School()
        {
            ViewBag.School = "active";
            return View();

        }

        [HttpPost]
        public ActionResult School(Admission admission)
        {
            using (var ctx = new SocietyContext())
            {
                ctx.Admissions.Add(admission);
                ctx.SaveChanges();
            }

            ViewBag.Message = '1';

            return View();

        }

//******************************************  Super Shop  ***************************************************//
        public ActionResult SuperShop()
        {
            ViewBag.SuperShop = "active";
            return View();
        }

        public ActionResult Cloth()
        {
            return View();
        }

        public ActionResult Food()
        {
            return View();
        }

        public ActionResult Medicine()
        {
            return View();
        }

        public ActionResult Necessery()
        {
            return View();
        }

        public ActionResult OrderForm(string data1, string data2)
        {
            ViewBag.Order = "active";
            ViewBag.Data1 = data1;
            ViewBag.Data2 = data2;
            return View();
        }

        [HttpPost]
        public ActionResult OrderForm(Order orderList)
        {

            string chan = (orderList.ProductAmount*Convert.ToInt32(orderList.Price)).ToString();

            ViewBag.Order = "active";
            orderList.CustomerId = Convert.ToInt32(Session["SocietyId"]);
            using (var ctx = new SocietyContext())
            {
                orderList.TotalPrice = chan + " " + "BDT";
                ctx.Orders.Add(orderList);
                ctx.SaveChanges();
            }
            ViewBag.Yes = '1';
            return View();
        }

        public ActionResult Purchases()
        {
            ViewBag.Purchases = "active";
            int id = Convert.ToInt32(Session["SocietyId"]);
            List<Order> ord = new List<Order>();
            using (var ctx = new SocietyContext())
            {
                var q =
                    ctx.Orders.Where(k => k.CustomerId == id)
                        .Select(c => new {c.ProductCode, c.ProductAmount, c.TotalPrice, c.Date});
                foreach (var d in q)
                {
                    Order ap = new Order();
                    ap.ProductCode = d.ProductCode;
                    ap.Date = d.Date;
                    ap.ProductAmount = d.ProductAmount;
                    ap.TotalPrice = d.TotalPrice;
                    ord.Add(ap);
                }
            }
            return View(ord);
        }

//*****************************************************  Clinic ***********************************************************//
        public ActionResult Clinic()
        {
            ViewBag.Clinic = "active";
            return View();
        }

        public ActionResult DoctorInformation()
        {
            ViewBag.DoctorInformation = "active";
            List<Specialist> categories;


            using (var ctx = new SocietyContext())
            {

                categories = ctx.Specialists.ToList();
            }

            ViewBag.Category = categories;

            return View();
        }

        public JsonResult GetAllDoctorInfoById(int id)
        {

            List<Doctor> doctor = new List<Doctor>();

            using (var ctx = new SocietyContext())
            {
                var a =
                    ctx.Doctors.Where(s => s.SpecialistId == id)
                        .Select(c => new {c.Id, c.Image, c.Name, c.Degree, c.Fees});
                ;
                foreach (var k in a)
                {
                    Doctor doc = new Doctor();
                    doc.Id = k.Id;
                    doc.Name = k.Name;
                    doc.Degree = k.Degree;
                    doc.Image = k.Image;
                    doc.Fees = k.Fees;
                    doctor.Add(doc);
                }
            }
            return Json(doctor);
        }

        public ActionResult Appointment()
        {
            ViewBag.Appointment = "active";
            List<Specialist> categories;


            using (var ctx = new SocietyContext())
            {

                categories = ctx.Specialists.ToList();
            }

            ViewBag.Category = categories;
            return View();
        }

        public JsonResult GetAllDoctorNameById(int id)
        {

            List<Doctor> doctors = new List<Doctor>();

            using (var ctx = new SocietyContext())
            {
                var a = ctx.Doctors.Where(s => s.SpecialistId == id);
                foreach (var k in a)
                {
                    Doctor doc = new Doctor();
                    doc.Id = k.Id;
                    doc.Name = k.Name;
                    doctors.Add(doc);
                }
            }
            return Json(doctors);
        }

        [HttpPost]
        public ActionResult Appointment(Appointment patientAppointment)
        {

            ViewBag.Appointment = "active";
            patientAppointment.PatientId = Convert.ToInt32(Session["SocietyId"]);
            List<Specialist> specialists;
            using (var db = new SocietyContext())
            {
                db.Appointments.Add(patientAppointment);
                db.SaveChanges();
                specialists = db.Specialists.ToList();
            }
            ViewBag.Category = specialists;
            ViewBag.Error = '1';
            return View();
        }

        public ActionResult AppointmentNotification()
        {
            ViewBag.AppointmentNotification = "active";
            int id = (int) Session["SocietyId"];

            List<AppointmentVeiw> appointmentList = new List<AppointmentVeiw>();
            using (var db = new SocietyContext())
            {
                ViewBag.Patient = db.SocietyRegistrations.FirstOrDefault(r => r.Id == id);
                var q = (from a in db.Appointments
                    join p in db.SocietyRegistrations on a.PatientId equals p.Id
                    join d in db.Doctors on a.DoctorId equals d.Id
                    join s in db.Specialists on a.SpecialistId equals s.Id
                    where a.PatientId == id
                    select new
                    {
                        appointmentDate = a.Date,
                        doctorName = d.Name,
                        docdesignation = d.Degree,
                        Special = s.Category,
                        aApproval = a.IsApproved
                    });
                foreach (var d in q)
                {
                    AppointmentVeiw ap = new AppointmentVeiw();
                    ap.Date = d.appointmentDate;
                    ap.DoctorName = d.doctorName;
                    ap.Designation = d.docdesignation;
                    ap.Specialist = d.Special;
                    ap.Approval = d.aApproval;
                    appointmentList.Add(ap);
                }
            }
            return View(appointmentList);
        }

//*************************************************  Security  ******************************************************//
        public ActionResult Security()
        {
            ViewBag.Security = "active";
            List<Security> selist = new List<Security>();
            using (var db = new SocietyContext())
            {
                selist = db.Securities.ToList();
            }
            ViewBag.Security = selist;
            return View();
        }

        //*************************************************Admin********************************************************//
        public ActionResult CustomersOrderlist()
        {
            ViewBag.CustomersOrderlist = "active";
            List<Orderview> orders = new List<Orderview>();
            using (var db = new SocietyContext())
            {
                var q = (from a in db.Orders
                    join p in db.SocietyRegistrations on a.CustomerId equals p.Id
                    where a.CustomerId == p.Id
                    select new
                    {
                        orderDate = a.Date,
                        customerName = p.Name,
                        Productcode = a.ProductCode,
                        totalPrice = a.TotalPrice,
                        productAmount = a.ProductAmount,
                        price = a.Price,
                        Contact = p.Mobile,
                        address = p.Address

Society/Views/Society/Clinic.cshtml
@{
    //Layout = null;
}


    <meta name="viewport" content="width=device-width" />
<title>Clinic</title>
<link href="~/Content/cliicstyle.css" rel="stylesheet" />
<style>
    .carousel-inner img {
        width: 100%;
        height: 550px;
    }
</style>
<script type="text/javascript">
    $('.carousel').carousel({
        interval: 1000
    }) </script>
<body>
<div id="demo" class="carousel slide" data-ride="carousel">

    <!-- Indicators -->
    <ul class="carousel-indicators">
        <li data-target="#demo" data-slide-to="0"></li>
        <li data-target="#demo" data-slide-to="1"></li>
        <li data-target="#demo" data-slide-to="2"></li>
        <li data-target="#demo" data-slide-to="3"></li>
        <li data-target="#demo" data-slide-to="4"></li>
    </ul>

    <!-- The slideshow -->
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="~/Picture/1.jpg" alt="Los Angeles">
        </div>
        <div class="carousel-item">
            <img src="~/Picture/2.jpg" alt="Chicago">
        </div>
        <div class="carousel-item">
            <img src="~/Picture/3.jpg" alt="New York">
        </div>
        <div class="carousel-item">
            <img src="~/Picture/4.jpg" alt="New York">
        </div>
        <div class="carousel-item">
            <img src="~/Picture/5.jpg" alt="New York">
        </div>
    </div>

    <!-- Left and right controls -->
    <a class="carousel-control-prev" href="#demo" data-slide="prev">
        <span class="carousel-control-prev-icon"></span>
    </a>
    <a class="carousel-control-next" href="#demo" data-slide="next">
        <span class="carousel-control-next-icon"></span>
    </a>
</div>


<div class="container">
    <div class="po1">
        <center>
            <strong id="po2">Services</strong>
        </center>
    </div><br>

    <div class="row">

        <div class="col-md-2"></div>
        <div class="col-md-4">
            <a style="text-decoration: none;" href="@Url.Action("DoctorInformation", "Society")">
                <div class="po3">
                    <h1 class="rounded-circle po4-img"><i class="fas fa-user-md"></i></h1>
                    <div class="po5">
                        <h2>
                            DOCTORS
                        </h2>

                    </div>

                </div>
            </a>
        </div>
        <div class="col-md-4">
            <a style="text-decoration: none;" href="@Url.Action("Appointment", "Society")">
                <div class="po3">
                    <h1 class="rounded-circle po4-img"><i class="fas fa-calendar-check"></i></h1>
                    <div class="po5">
                        <h2>
                            APPOINTMENT
                        </h2>

                    </div>

                </div>
            </a>
        </div>
        <div class="col-md-2"></div>
    </div>

   
</div>
    
       

        <!-- gallery -->
        <div class="gallery-cont text-center pb-5" id="gallery">
            <div class="container py-xl-5 py-lg-3">
                <h3 class="title-w3 mb-sm-5 mb-4 text-center text-bl font-weight-bold">Clinic Gallery</h3>
                <div class="row news-grids text-center no-gutters">
                    <div class="col-md-4 gal-img">
                        <a href="#gal1"><img src="~/Picture/mgal1.jpg" alt="Gallery Image" class="img-fluid"></a>
                    </div>
                    <div class="col-md-4 gal-img">
                        <a href="#gal2"><img src="~/Picture/mgal2.jpg" alt="Gallery Image" class="img-fluid"></a>
                    </div>
                    <div class="col-md-4 gal-img">
                        <a href="#gal3"><img src="~/Picture/mgal3.jpg" alt="Gallery Image" class="img-fluid"></a>
                    </div>
                </div>
                <div class="row news-grids text-center no-gutters">
                    <div class="col-md-4 gal-img">
                        <a href="#gal4"><img src="~/Picture/mgal4.jpg" alt="Gallery Image" class="img-fluid"></a>
                    </div>
                    <div class="col-md-4 gal-img">
                        <a href="#gal5"><img src="~/Picture/mgal5.jpg" alt="Gallery Image" class="img-fluid"></a>
                    </div>
                    <div class="col-md-4 gal-img">
                        <a href="#gal6"><img src="~/Picture/mgal6.jpg" alt="Gallery Image" class="img-fluid"></a>
                    </div>
                </div>
                <div class="row news-grids text-center no-gutters">
                    <div class="col-md-4 gal-img">
                        <a href="#gal7"><img src="~/Picture/mgal7.jpg" alt="Gallery Image" class="img-fluid"></a>
                    </div>
                    <div class="col-md-4 gal-img">
                        <a href="#gal8"><img src="~/Picture/mgal8.jpg" alt="Gallery Image" class="img-fluid"></a>
                    </div>
                    <div class="col-md-4 gal-img">
                        <a href="#gal9"><img src="~/Picture/mgal9.jpg" alt="Gallery Image" class="img-fluid"></a>
                    </div>
                </div>

            </div>
        </div>
        <!-- //gallery -->
</body>
@section scripts{

}

Society/Views/Society/DoctorAppointment.cshtml
@{
    //Layout = null;
}

    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/DataTables/css/dataTables.bootstrap.css" rel="stylesheet" />
    <link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-datepicker.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-datepicker.css" rel="stylesheet" />
    <title>DoctorAppointment</title>

    <style>
        .tdname {
            font-size: 20px;
            padding-right: 14px;
        }

        .tdvalue {
            width: 237px;
            border: 2px solid #2c3e50;
            border-radius: 10px;
            height: 40px;
            margin-top: 10px;
        }

        #tddate {
            width: 237px;
            border: 2px solid #2c3e50;
            border-radius: 10px;
            height: 40px;
            margin-top: 10px;
        }

        .am1 {
            margin-top: 30px;
        }

        .up {
            margin-top: 50px;
        }

        .but {
           
            width: 160px;
            height: 45px;
            margin-top: 15px;
        }

        .appr {
            background-color: green;
            color: white;
            text-align: center;
            padding-top: 12px;
        }

        .normal {
            background-color: #662a6bdb;
            color: white;
            text-align: center;
            padding-top: 12px;
        }

        .appointmentlist {
            margin-bottom: 30px;
        }

        #apprbtn {
            background: green;
        }
        .app {
            text-align: center;
            padding: 1em;
            background-color: beige;
            font-weight: 700;
            font-size: 30px;
            color: blue;
        }
        .headdesign1 {
            background-color: #df5878;
            color: white;
        }
    </style>
<body>
<div class="container">
    <p class="app">Appointmet List</p>
    <div class="appointmentlist">

        <form action="" method="POST">
            <center>
                <table class="up">
                    <tr>
                        <td class="tdname">Date:</td>
                        <td>
                            <input type="text" class="form-control" id="tddate" placeholder="Date" required="" autocomplete="off"/>
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>
                            <center>
                                <button class="btn btn-primary but" id="searchbtn" style="">Search</button>
                            </center>

                        </td>
                    </tr>
                </table>
            </center>

        </form>
        <div class="row am1">

            <div class="col-md-12 design">
                <table class="table table-bordered table-striped table-hover" id="apptable">
                    <thead class="headdesign1">
                    <tr>
                        <th>Serial No</th>
                        <th>Patient Name</th>
                        <th>Doctor Name</th>
                        <th>Specialist</th>
                        <th>Degree</th>
                    </tr>
                    </thead>
                    <tbody id="tableBody"></tbody>

                </table>
            </div>

        </div>
    </div>
</div>
</body>
@section scripts
{
    <script src="~/Scripts/jquery-3.0.0.min.js"></script>

    <script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/bootstrap-datepicker.min.js"></script>
    <script src="~/Scripts/bootstrap-datepicker.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            var table = $('#apptable').DataTable();
            var asiaTime = new Date().toLocaleString("en-US", { timeZone: "Asia/Dhaka" });
            var date = new Date(asiaTime);
            $('#tddate').datepicker({
                startDate: date,
                autoclose: true,
                todayHighlight: true
            });

            $('#searchbtn').on('click', function () {
                table.clear();
                var date = $('#tddate').val();
                var serialNo = 1;
                var json = { date: date };
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetAppointments", "Society")',
                    contentType: 'application/json',
                    data: JSON.stringify(json),
                    success: function (response) {

                        $.each(response, function (key, value) {
                            table.row.add([
                                serialNo,
                                value.PatientName,
                                value.DoctorName,
                                value.Specialist,
                                value.Designation
                            ]).draw(false);
                            serialNo += 1;
                        });

                    }

                });
                return false;
            });




        });
    </script>
}

Society/Views/Society/DoctorInformation.cshtml
@using Society.Models

@{
    //Layout = null;
    List<Specialist> specialist = ViewBag.Category;
}



    <meta name="viewport" content="width=device-width" />
<title>DoctorInformation</title>
<link href="~/Content/DataTables/css/dataTables.bootstrap.css" rel="stylesheet" />
<link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />
<style>
    #SpecialistId {
        float: right;
        margin-right: 3px;
        width: 270px;
        height: 45px;
        border: 2px solid #2c3e50;
    }

    .coldesign {
        margin-top: 20px;
        margin-bottom: 10px;
        height: inherit;
        text-align: center;
        padding: 1em;
        background-color: aliceblue;
        font-weight: 500;
        font-size: 20px;
    }

    .design {
        border-radius: 20px;
        margin-top: 50px;
        height: inherit;
        margin: 10px;
        padding: 12px;
        text-align: center;
        /*border: 3px solid green;*/
    }
    #top {
        width: 130px;
        height: 120px;
    }
    .dtable {
        margin-top: 80px;
        margin-bottom: 130px;
        box-shadow: 2px 2px 8px black;
        border-radius: 1px 15px;
        padding: 25px;
    }
    .dd {
        background-color: brown;
        color: white;
    }
    #na {
        padding-top: 45px;
    }
</style>

<body>
    <div class="container dtable">
        <div class="row">
            <div class="col-md-12 coldesign">
                <center>
                    <form method="POST">
                        <table>
                            <tr>
                                <td>
                                    <select id="SpecialistId" name="Id" >
                                        <option value="">Select a category</option>
                                        @foreach (Specialist sp in specialist)
                                        {
                                            <option value="@sp.Id">@sp.Category</option>
                                        }
                                    </select>
                                </td>
                            </tr>
                        </table>

                    </form>
                </center>

            </div><br>
        </div>
        <div class="row">
            <div class="col-md-12 design">
                <table class="table table-bordered table-striped table-hover" id="doctortable">
                    <thead>
                        <tr class="dd">
                            <th>Image</th>
                            <th>Name</th>
                            <th>Degree</th>
                            <th>Fess</th>
                        </tr>
                    </thead>
                    <tbody id="tableBody">
                    
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</body>
@section scripts
{

    <script src="~/Scripts/jquery-3.0.0.min.js"></script>
    <script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            var table = $('#doctortable').DataTable();
            $('#SpecialistId').on('change', function () {
                var deptId = $('#SpecialistId').val();
                table.clear().draw(false);
                var json = { id: deptId };
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetAllDoctorInfoById", "Society")',
                    contentType: 'application/json',
                    data: JSON.stringify(json),
                    success: function (response) {
                        $.each(response, function (key, value) {
                            table.row.add([
                                "<img src=/" + value.Image + " id=\"top\">",
                                "<h5 id=\"na\">" + value.Name + "</h5>",
                                "<h5 id=\"na\">" + value.Degree + "</h5>",
                                "<h5 id=\"na\">" + value.Fees + "</h5>"
                            ]).draw(false);
                        });
                    }
                });
            });
        });
    </script>
}