Society/Controllers/DoctorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Society.Models;
using Society.Context;

namespace Society.Controllers
{
    public class DoctorController : Controller
    {
        private SocietyContext db = new SocietyContext();

        // GET: /Doctor/
        public ActionResult DocIndex()
        {
            ViewBag.DocIndex = "active";
            return View(db.Doctors.ToList());
        }

        // GET: /Doctor/Create
        public ActionResult Create()
        {
            ViewBag.Doc = db.Specialists.ToList();
            return View();
        }

        // POST: /Doctor/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Image,Degree,Fees,SpecialistId")] Doctor doctor, HttpPostedFileBase Image)
        {
            if (ModelState.IsValid)
            {
                if (Image != null && Image.ContentLength > 0)
                {

                    try
                    {
                        string fileName = Guid.NewGuid().ToString() + System.IO.Path.GetExtension(Image.FileName);
                        string uploadUrl = Server.MapPath("~/Picture");
                        Image.SaveAs(Path.Combine(uploadUrl, fileName));
                        doctor.Image = "Picture/" + fileName;
                    }
                    catch (Exception ex)
                    {
                        ViewBag.Message = "ERROR:" + ex.Message.ToString();
                    }
                }
                doctor.Name = doctor.Name;
                doctor.SpecialistId = doctor.SpecialistId;
                doctor.Degree = doctor.Degree;
                doctor.Fees = doctor.Fees;
                db.Doctors.Add(doctor);
                db.SaveChanges();

            }

            return RedirectToAction("Create", new { message = "Doctor added Successfully" });
        }

        // GET: /Doctor/Edit/5
        public ActionResult Edit(int? id)
        {
            ViewBag.Doc = db.Specialists.ToList();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doctor doctor = db.Doctors.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
           
            return View(doctor);
        }

        // POST: /Doctor/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Image,Degree,Fees,SpecialistId")] Doctor doctor, HttpPostedFileBase Image, string pastImage)
        {
            doctor.Image = pastImage;
            if (Image != null && Image.ContentLength > 0)
            {
                string fullPath = Request.MapPath("~/" + pastImage);
                if (System.IO.File.Exists(fullPath))
                {
                    System.IO.File.Delete(fullPath);
                }
                try
                {
                    string fileName = Guid.NewGuid().ToString() + System.IO.Path.GetExtension(Image.FileName);
                    string uploadUrl = Server.MapPath("~/Picture");
                    Image.SaveAs(Path.Combine(uploadUrl, fileName));
                    doctor.Image = "Picture/" + fileName;
                }
                catch (Exception ex)
                {
                    ViewBag.Error = "ERROR:" + ex.Message.ToString();
                }
            }
            if (ModelState.IsValid)
            {
                db.Entry(doctor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("DocIndex");
            }
            return View(doctor);
        }

        // GET: /Doctor/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doctor doctor = db.Doctors.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }

        // POST: /Doctor/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Doctor doctor = db.Doctors.Find(id);
            db.Doctors.Remove(doctor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Society/Controllers/HouseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Society.Models;
using Society.Context;

namespace Society.Controllers
{
    public class HouseController : Controller
    {
        private SocietyContext db = new SocietyContext();

        // GET: /House/
        public ActionResult HouseIndex()
        {
            ViewBag.Index = "active";
            return View(db.Houses.ToList());
        }

        // GET: /House/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /House/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,HouseNo,Image,Information,Price")] House house, HttpPostedFileBase Image)
        {
            if (ModelState.IsValid)
            {
                if (Image != null && Image.ContentLength > 0)
                {
                    try
                    {
                        string fileName = Guid.NewGuid().ToString() + System.IO.Path.GetExtension(Image.FileName);
                        string uploadUrl = Server.MapPath("~/Picture");
                        Image.SaveAs(Path.Combine(uploadUrl, fileName));
                        house.Image = "Picture/" + fileName;
                    }
                    catch (Exception ex)
                    {
                        ViewBag.Message = "ERROR:" + ex.Message.ToString();
                    }
                }
                house.HouseNo = house.HouseNo;
                house.Information = house.Information;
                house.Price = house.Price;
                db.Houses.Add(house);
                db.SaveChanges();

            }

            return RedirectToAction("Create", new { message = "House added Successfully" });
        }

        // GET: /House/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            House house = db.Houses.Find(id);
            if (house == null)
            {
                return HttpNotFound();
            }
            return View(house);
        }

        // POST: /House/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,HouseNo,Image,Information,Price")] House house, HttpPostedFileBase Image, string pastImage)
        {
            if (ModelState.IsValid)
            {
                if (Image != null && Image.ContentLength > 0)
                {

                    try
                    {
                        string fileName = Guid.NewGuid().ToString() + System.IO.Path.GetExtension(Image.FileName);
                        string uploadUrl = Server.MapPath("~/Picture");
                        Image.SaveAs(Path.Combine(uploadUrl, fileName));
                        house.Image = "Picture/" + fileName;
                    }
                    catch (Exception ex)
                    {
                        ViewBag.Message = "ERROR:" + ex.Message.ToString();
                    }
                }
                else
                {
                    house.Image = pastImage;
                }
                db.Entry(house).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("HouseIndex");
            }
            return View(house);
        }

        // GET: /House/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            House house = db.Houses.Find(id);
            if (house == null)
            {
                return HttpNotFound();
            }
            return View(house);
        }

        // POST: /House/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            House house = db.Houses.Find(id);
            db.Houses.Remove(house);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Society/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Society</title>
    <link href="http://fonts.googleapis.com/css?family=Cookie" rel="stylesheet" type="text/css">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/fontawesome-all.min.css" rel="stylesheet" />
</head>
<body>
    <nav style="background-color: #34404c;" class="navbar navbar-expand-lg navbar-dark">
        <a class="navbar-brand myclass" href="#">
            <i style="font-size: 30px;" class="logo"></i>
            Society Management System
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="menual collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">

            @if (Session["SocietyId"] == null && Session["AdminId"] == null)
            {
                <div class="navbar-nav">
                    <a class="nav-item nav-link  @ViewBag.Index" href="@Url.Action("Index","Society")">Home <span class="sr-only">(current)</span></a>
                    <a class="nav-item nav-link  @ViewBag.Login" href="@Url.Action("Login","Authentication")">Login</a>
                    <a class="nav-item nav-link  @ViewBag.Registration" href="@Url.Action("Registration", "Authentication")">Register</a>
                </div>
            }
          @if (Session["SocietyId"] != null)
            {
                 <div class="navbar-nav">
                    <a class="nav-item nav-link  @ViewBag.Index" href="@Url.Action("Index","Society")">Home <span class="sr-only">(current)</span></a>
                     <a class="nav-item nav-link @ViewBag.HouseRent " href="@Url.Action("HouseRent", "Society")">House</a>
                     <a class="nav-item nav-link @ViewBag.SuperShop " href="@Url.Action("SuperShop","Society")">SuperShop</a>
                     <a class="nav-item nav-link @ViewBag.School" href="@Url.Action("School", "Society")">School</a>
                     <a class="nav-item nav-link @ViewBag.Clinic" href="@Url.Action("Clinic", "Society")">Clinic</a>
                     <a class="nav-item nav-link @ViewBag.Security" href="@Url.Action("Security", "Society")">Security</a>
                     <a class="nav-item nav-link @ViewBag.Purchases" href="@Url.Action("Purchases", "Society")">Purchases</a>
                     <a class="nav-item nav-link @ViewBag.AppointmentNotification" href="@Url.Action("AppointmentNotification", "Society")">Profile</a>
                     <a class="nav-item nav-link " href="@Url.Action("Logout", "Authentication")">Logout</a>
                </div>
            }
            @if (Session["AdminId"] != null)
            {
                <div class="navbar-nav">
                <a class="nav-item nav-link @ViewBag.Index" href="@Url.Action("Index", "Society")"><i class="fas fa-home"></i>Home <span class="sr-only">(current)</span></a>
                <a class="nav-item nav-link @ViewBag.DocIndex" href="@Url.Action("DocIndex", "Doctor")">Doctor</a>
                <a class="nav-item nav-link @ViewBag.HouseIndex" href="@Url.Action("HouseIndex", "House")">House</a>
                <a class="nav-item nav-link @ViewBag.SecuIndex" href="@Url.Action("SecuIndex", "Security")">Security</a>
                <a class="nav-item nav-link @ViewBag.CustomersOrderlist" href="@Url.Action("CustomersOrderlist", "Society")">Order</a>
                <a class="nav-item nav-link @ViewBag.DoctorAppointment" href="@Url.Action("DoctorAppointment", "Society")">Appointment</a>
                <a class="nav-item nav-link " href="@Url.Action("AdminLogout", "Authentication")">Logout</a>
                </div>
            }
        </div>
    </nav>

        @RenderBody()
    <footer class="footer-distributed">

        <div class="footer-left">

            <h3>Society</h3>

            <p class="footer-links">
                We are dedicate to providing the best possible<br> facilities for people.
            </p>

            <p class="footer-company-name">2020</p>
        </div>

        <div class="footer-center">

            <div>
                <i class="fa fa-map-marker"></i>
                <p><span>Chaktai Street</span> chaktai, Chittagong</p>
            </div>

            <div>
                <i class="fa fa-phone"></i>
                <p>+015623489</p>
            </div>

            <div>
                <i class="fa fa-envelope"></i>
                <p><a href="#">elegant@gmail.com</a></p>
            </div>

        </div>

        <div class="footer-right">

            <p class="footer-company-about">
                <span>About the company</span>
                Chandrasree Das Gupta.
            </p>

            <div class="footer-icons">

                <a href="#"><i class="fab fa-facebook-f"></i></a>
                <a href="#"><i class="fab fa-twitter"></i></a>
                <a href="#"><i class="fab fa-linkedin-in"></i></a>
                <a href="#"><i class="fab fa-github"></i></a>

            </div>

        </div>

    </footer>
</body>
</html>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)